name: Build a Node.js project.

on:
  workflow_call:
    inputs:
      setup:
        type: string
        default: "echo ''"
        required: false
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  node_build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: ${{ inputs.setup }}
      - run: npm ci
      - run: make
      - run: npm run -s test -- --reporter tap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
